---
#-------------------------------
# General Site Settings

title: 
logo:
author: themefisher
description: this is meta description
email: msjulietruong@gmail.com
phone: 
address: 
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" } #merge about and front page 
  - { name: Experience, link: "/blog" }  #FOCAL POINT, add resume
  - { name: Portfolio, link: "/portfolio" }  #add website, data science, and mini proj
  - { name: Contact, link: "/contact" } #remove

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m Julie, <br> a Computer Science Student!

social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/msjulietruong/" }
  - { icon: "ti-github", link: "https://github.com/msjulietruong" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Currently I am a Computer Science student at Cypress College. After transferring, I hope to graduate with a Bachelors in Computer Science. I am open to more opportunities regarding tech!

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section  make this bout hobbies
work-process:
  - title: "Digital Art"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Photography"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Movies"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


#-------------------------------
# Skills Section


#-------------------------------
# Experience Section, move to Resume too!


#-------------------------------
# Education Section # will move to Resume, include pdf link to resume

#-------------------------------
# Services Section  #hobbies section

services-title: Hobbies
services:
  - {
      name: Digital Art,
      icon: ti-palette,
      description: "When I'm not coding, I love making art for the people I care about.",
      active: ,# Add true to select section
    }
  - {
      name: Movies,
      icon: ti-vector,
      description: "Movies are an amazing way to delve into new worlds.",
      active: true, # Add true to select section
    }
  - {
      name: Reading,
      icon: ti-panel,
      description: "My favorite book is Perks of Being A Wallflower.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "https://devpost.com/software/zotpeterzot-by-fabfour"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "PROJECTS", type: "projects" }
  - { title: "DATA SCIENCE", type: "data science" }
  - { title: "EXTRACURRICULAR", type: "extracurricular" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "projects"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "data science"

  - image: "assets/images/portfolio/item-3.png"
    url: "https://devpost.com/software/zotpeterzot-by-fabfour"
    portfolio-type:
      - type: "extracurricular"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"
    portfolio-type: 
     - type: "projects"

#-------------------------------
# Testimonials Section


#-------------------------------
# Client Slider Section


#-------------------------------
# Contact Section

